# Common
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/temporary_project
      driver-class-name: org.mariadb.jdbc.Driver
      username: temp
      password: temp
mybatis:
  configuration:
    map-underscore-to-camel-case: true
